#!/usr/bin/fish
set -x BASE_URL "/idris2-quickdocs"
cd (status dirname)
pushd site
yarn build
cd build
or exit 1
popd

if test ! -e cache
    git worktree add cache gh-pages
    or begin
        echo local gh-pages branch does not exist
        git fetch origin gh-pages
        echo Please try again now
        exit 1
    end
end

rsync -a site/build/ cache/

pushd cache
touch .nojekyll
git add .
and git commit -m "Update"
and git push
popd
