#!/usr/bin/env fish
### archive website for offline use

cd build
rm data/archive.tar.xz
and tar --mtime=0000000000 --{owner,group}=root --exclude "data/*.tar.gz" --exclude "data/archive.tar.gz" -cvJf ../../data/archive.tar.xz .
cp ../../data/archive.tar.xz data/archive.tar.xz
